name: Auto Build APK
on:
  push:
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      # 自动生成 gradlew 脚本
      - name: Generate Gradle Wrapper
        run: |
          java -cp $(find ~/.gradle -name gradle-wrapper.jar | head -1) org.gradle.wrapper.GradleWrapperMain --gradle-version 8.1

      # 赋予执行权限
      - name: Grant execute permission
        run: chmod +x gradlew

      # 编译APK
      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoBoot_APK_Release
          path: app/build/outputs/apk/release/*.apk
