name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup JDK17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 下载官方指定版本gradle，用来生成wrapper，版本和项目保持8.2
      - name: Setup Gradle tool 8.2
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.2'

      # 生成wrapper，产出 gradle-wrapper.jar
      - name: Generate gradle wrapper
        run: gradle wrapper --gradle-version 8.2

      - name: chmod +x gradlew
        run: chmod +x gradlew

      - name: assembleDebug
        run: ./gradlew assembleDebug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
