name: Auto Build APK
on:
  push:
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      # 拉取源码
      - name: Checkout code
        uses: actions/checkout@v4

      # 配置JDK17 + 自动修复gradle wrapper
      - name: Setup JDK 17 & Gradle
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle
      - name: Fix Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      # 赋予执行权限
      - name: Grant execute permission
        run: chmod +x gradlew

      # 编译Release包
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # 上传APK
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoBoot_APK_Release
          path: app/build/outputs/apk/release/*.apk
